spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot-mysql
    driver-class-name: com.mysql.jdbc.Driver
    type: 
  sql:
    init:
      schema-locations: classpath*:schema-all.sql